const { bot, commands } = require("./plugins");
let config = require("../config");
const {
  getBuffer,
  decodeJid,
  parseJid,
  parsedJid,
  getJson,
  isUrl,
  getUrl,
  qrcode,
  secondsToDHMS,
  formatBytes,
  sleep,
  clockString,
  validateQuality,
  runtime,
  AddMp3Meta,
  isNumber,
  getRandom,
  toAudio,
  readQr,
  getLyrics,
  isAdmin,
} = require("./functions");
const { serialize, downloadMedia } = require("./serialize");
module.exports = {
  toAudio,
  isPrivate: config.WORK_TYPE.toLowerCase() === "private",
  isAdmin,
  serialize,
  getLyrics,
  readQr,
  downloadMedia,
  getRandom,
  Function: bot,
  bot,
  commands,
  getBuffer,
  decodeJid,
  parseJid,
  parsedJid,
  getJson,
  isUrl,
  getUrl,
  validateQuality,
  qrcode,
  secondsToDHMS,
  formatBytes,
  sleep,
  clockString,
  runtime,
  AddMp3Meta,
  isNumber,
};
